fix: revert broken async custom code (#80)
reverting because this change worked for single requests, but multiple
in a row fail with:
```
Traceback (most recent call last):
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/clients/openapi_client.py", line 42, in wrapped
    (result, status, headers) = await method(*args, **kwargs)
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/openapi/frontrunner_api/api_client.py", line 150, in __call_api
    response_data = await self.request(
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/openapi/frontrunner_api/rest.py", line 181, in GET
    return (await self.request("GET", url,
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/openapi/frontrunner_api/rest.py", line 167, in request
    async with pm.request(**args) as r:
  File "/Users/brianvanderschaaf/.pyenv/versions/3.9.9/envs/frontrunner-sdk/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/brianvanderschaaf/.pyenv/versions/3.9.9/envs/frontrunner-sdk/lib/python3.9/site-packages/aiohttp/client.py", line 400, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/test.py", line 80, in <module>
    asyncio.run(main())
  File "/Users/brianvanderschaaf/.pyenv/versions/3.9.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/brianvanderschaaf/.pyenv/versions/3.9.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/test.py", line 13, in main
    response = await sdk.frontrunner.get_markets(id="50f14154-31f1-44b1-ab90-b8041e45b07f")
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/facades/frontrunner.py", line 80, in get_markets
    return await self._run_operation(GetMarketsOperation, self.deps, request)
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/facades/base.py", line 18, in _run_operation
    return await operation.execute(deps)
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/logging/log_operation.py", line 22, in wrapped
    value = await operation(instance, deps)
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/commands/frontrunner/get_markets.py", line 38, in execute
    markets = await deps.openapi_frontrunner_api.get_markets(**request)
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/clients/openapi_client.py", line 66, in wrapped
    (response, _, _) = await method(*args, **kwargs)
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/clients/openapi_client.py", line 90, in wrapped
    result = await method(*args, **kwargs)
  File "/Users/brianvanderschaaf/Documents/frontrunner/projects/frontrunner-sdk/frontrunner_sdk/clients/openapi_client.py", line 45, in wrapped
    raise FrontrunnerUnserviceableException("OpenAPI Framework Exception") from cause
frontrunner_sdk.exceptions.FrontrunnerUnserviceableException: OpenAPI Framework Exception
```